require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
   - 'spec/**/*'

Rails/Output:
  Enabled: true
  Exclude:
    - 'db/seeds.rb'
