default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV["TEST_DATABASE_URL"] || ENV['DATABASE_URL'] %>

production:
  <<: *default
